# Generated by Django 5.2.7 on 2025-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34, null=True, unique=True)),
                ('is_mine', models.BooleanField(default=False)),
            ],
        ),
    ]
