# Generated by Django 5.2.7 on 2025-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
    ]
