# Generated by Django 5.2.7 on 2025-10-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_account_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_id',
        ),
    ]
