# Generated by Django 5.2.7 on 2025-10-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_transaction_receiver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='manager.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='manager.account'),
        ),
    ]
