# Generated by Django 5.2.7 on 2025-10-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_transaction_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='manager.transaction'),
        ),
    ]
