# Generated by Django 4.2.25 on 2025-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_transaction_is_refund_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='start_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
