# Generated by Django 4.2.25 on 2025-10-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_account_start_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_refund_of',
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_transaction_refunds', to='manager.transaction')),
                ('refund_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transaction_refunds', to='manager.transaction')),
            ],
        ),
    ]
