# Generated by Django 4.2.25 on 2025-10-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refunds',
            new_name='Refund',
        ),
    ]
