# Generated by Django 4.2.25 on 2025-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi bi-tags', max_length=50),
        ),
    ]
