# Generated by Django 4.2.25 on 2025-12-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='manager.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='manager.account'),
            preserve_default=False,
        ),
    ]
