# Generated by Django 4.2.25 on 2025-12-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_transaction_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
