# Generated by Django 4.2.25 on 2025-12-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
    ]
