# Generated by Django 4.2.27 on 2026-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='account_icons/'),
        ),
    ]
