# Generated by Django 4.2.27 on 2026-01-25 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='account_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
    ]
