# Generated by Django 4.2.27 on 2026-01-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_account_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_splits', to='manager.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='manager.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Split',
                'verbose_name_plural': 'Transaction Splits',
                'unique_together': {('transaction', 'category')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='transactions', through='manager.TransactionSplit', to='manager.category'),
        ),
    ]
