# Generated by Django 4.2.27 on 2026-01-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20260128_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
