# Generated by Django 4.2.27 on 2026-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remainder_after_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remainder_of_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
