# Generated by Django 4.2.27 on 2026-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_transaction_remainder_after_refunds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
