# Generated by Django 4.2.27 on 2026-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_account_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='iban',
            new_name='account_nr',
        ),
    ]
