# Generated by Django 4.2.27 on 2026-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_usersettings_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='future_transactions_in_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('auto', 'System Default'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10),
        ),
    ]
